<a href="https://colab.research.google.com/github/iammiori/AI_19_SS_CLASS/blob/master/multi_variable_linear_regression_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# google mount
from google.colab import drive
import os
if os.path.exists('/content/gdrive')==False:
  drive.mount('/content/gdrive')
  print("Google Drive is mounted")
else:
  print("Already mounted")

Already mounted


In [0]:
import tensorflow as tf
tf.set_random_seed(777)

In [8]:
# 입력 출력 데이터 행렬로 정의
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholer
# none : 입력해주는 대로 받겠다.
# matrix 니까 shape써줌
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

# W, b 설정
W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis
# 행렬의 곱이기 때문에 tf.matmul 사용

hypothesis = tf.matmul(X,W) + b

# cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# 최적화 위해 gradient descent & minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# session open, execute
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 학습 시작
for step in range(10001):
  cost_val, hy_val, _ = sess.run([cost,hypothesis, train],
                                feed_dict={X: x_data, Y: y_data})
  
  if (step % 1000 ==0):
    print("step :{} cost : {} prediction \n{}".format(step, cost_val, hy_val))

step :0 cost : 89865.5859375 prediction 
[[-124.822495]
 [-128.20485 ]
 [-138.01988 ]
 [-146.00453 ]
 [ -95.689354]]
step :1000 cost : 25.371524810791016 prediction 
[[143.25471]
 [189.95967]
 [177.58372]
 [197.35243]
 [146.2558 ]]
step :2000 cost : 15.922884941101074 prediction 
[[144.90034]
 [188.8397 ]
 [178.09839]
 [197.64362]
 [144.85454]]
step :3000 cost : 10.37509536743164 prediction 
[[146.16331]
 [187.98192]
 [178.49559]
 [197.85172]
 [143.79573]]
step :4000 cost : 7.098494529724121 prediction 
[[147.13423]
 [187.32411]
 [178.80304]
 [197.99672]
 [142.99783]]
step :5000 cost : 5.145158767700195 prediction 
[[147.88228]
 [186.81895]
 [179.04198]
 [198.094  ]
 [142.39868]]
step :6000 cost : 3.9636778831481934 prediction 
[[148.46016]
 [186.43025]
 [179.22855]
 [198.15517]
 [141.95088]]
step :7000 cost : 3.2332637310028076 prediction 
[[148.9081 ]
 [186.13048]
 [179.37508]
 [198.18912]
 [141.61829]]
step :8000 cost : 2.7672336101531982 prediction 
[[149.25676]
 [185.89857]
 [179.