<a href="https://colab.research.google.com/github/iammiori/AI_19_SS_CLASS/blob/master/0411_1_multinomial_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive

import os

if os.path.exists('/content/gdrive')==False:
  drive.mount('/content/gdrive')
  print('Google Drive is mounted\n')
else:
  print('Google Drive is already mounted\n')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive
Google Drive is mounted



In [0]:
import tensorflow as tf
tf.set_random_seed(777)

# tensorflow 를 impoty 하고, random 값 고정

# 데이터 셋 지정 

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
# x_data : (3,8)

y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
# y_data : (3,8)

# 평가용 데이터 셋
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]

y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

# placeholder 설정
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
#tf.float32 도 가능

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# hypothesis
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
# softmax 인자 logits (logits = tensor 형)
# softmax : binary classfication 을 여러번 결합한 결과
# 입력을 sigmoid와 마찬가지로 0과 1사이 값으로 변화
# 변환된 결과에 대한 합계가 1이 되도록 만들어줌
# score 나와 (ex= minist 에서 9가 보여줬을 때, 8일 확률 몇, 9일 확률 몇)

# cost function , Optimizer
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
# ( , one-hot-encoding)
# one-hot-encoding : 단 하나의 값만 True 고 나머지 모두 False
# argmax 쓰는 이유는 확률 몇몇 보다는 가장 큰 확률을 1 나머지는 0으로 만들고 싶어서
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
# 맞는지 비교
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
# tf.cast => tensor 를 새로운 형태로 캐스팅
#print("accuracy :\n{}\n".format(accuracy))

with tf.Session() as sess:

    sess.run(tf.global_variables_initializer())
# session 실행
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
    

0 13.794874 [[-0.39821994  0.3877694   0.8202615 ]
 [ 0.3672454  -2.250823    1.4062666 ]
 [ 1.1104854  -1.2924523   0.47341397]]
1 10.276665 [[-0.3843226   0.42526442  0.76886916]
 [ 0.5002204  -2.075833    1.0983016 ]
 [ 1.224211   -1.1049573   0.17219341]]
2 8.397062 [[-0.42726272  0.46274364  0.7743301 ]
 [ 0.35067448 -1.9008749   1.0728894 ]
 [ 1.0492762  -0.9174784   0.15964916]]
3 7.3202267 [[-0.44527283  0.5001984   0.7548854 ]
 [ 0.33324388 -1.725966    0.91541123]
 [ 1.0001799  -0.7300248   0.02129201]]
4 6.277843 [[-0.4829546   0.5375703   0.75519526]
 [ 0.21000135 -1.5512263   0.8639141 ]
 [ 0.85004514 -0.54265964 -0.01593839]]
5 5.232539 [[-0.5035311   0.5747718   0.7385702 ]
 [ 0.17699863 -1.3768401   0.7225307 ]
 [ 0.78676087 -0.35550183 -0.13981189]]
6 4.20114 [[-0.5385943   0.61142945  0.73697585]
 [ 0.06551839 -1.2036119   0.66078264]
 [ 0.64859784 -0.16910224 -0.18804845]]
7 3.1836972 [[-0.55977994  0.6466607   0.72293025]
 [ 0.02551965 -1.0335675   0.53073704]
 [ 0.

- 1.5 => nan 값 많음
- 1e-10 => 1.0
-  0.1 => 1.0
- 적당한 learning rate 찾는 과정
- 1.5 는 너무크고
- 1e-10 은 너무 작고
- 0.1 이 적당하겠다.
- **이거 찾는거 중요**