<a href="https://colab.research.google.com/github/iammiori/AI_19_SS_CLASS/blob/master/0411_2_normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
import os

if os.path.exists('/content/gdrive')==False:
  drive.mount('/content/gdrive')
  print('Google Drive is mounted\n')
else:
  print('Google Drive is already mounted\n')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive
Google Drive is mounted



In [0]:
import tensorflow as tf
import numpy as np
#from sklearn.preprocessing import MinMaxScaler
# min_max_scalar 를 쓰기 위해 import

 

tf.set_random_seed(777)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

#print(xy)

# feature 값의 스케일이 크면 학습이 이루어지지 않고 발산하기 쉬움
# min_max_scaler는 최댓값은 1 최소값을 0으로 하여, 그사이에 값들이 있도록 하는 방법이다
# 방법은 Xscale = (X-Xmin) / (Xmax-Xmin)


def Min_Max_Scaler(xy):
    max=np.max(xy)
    min=np.min(xy)
    scale=(xy-min)/(max-min)
    return scale
    
xy = Min_Max_Scaler(xy)
#print(xy)

#print("xy : \n{}\n".format(xy))

# data slicing
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]



#print('x_data:\n{}\n'.format(x_data))

# placeholder
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

# weight, bias 설정
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis 와 cost 설정
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# GradientDescent 최적화
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

                   

0 Cost:  0.072479784 
Prediction:
 [[0.03994584]
 [0.53036964]
 [0.3224765 ]
 [0.09326065]
 [0.18921113]
 [0.19454283]
 [0.1412409 ]
 [0.30116093]]
1 Cost:  0.07247646 
Prediction:
 [[0.03993952]
 [0.53036153]
 [0.32246917]
 [0.09325415]
 [0.18920428]
 [0.19453597]
 [0.14123422]
 [0.30115366]]
2 Cost:  0.07247314 
Prediction:
 [[0.03993323]
 [0.5303534 ]
 [0.32246184]
 [0.09324765]
 [0.18919742]
 [0.19452912]
 [0.14122754]
 [0.3011464 ]]
3 Cost:  0.072469816 
Prediction:
 [[0.03992692]
 [0.5303453 ]
 [0.3224545 ]
 [0.09324116]
 [0.18919057]
 [0.19452226]
 [0.14122087]
 [0.30113912]]
4 Cost:  0.0724665 
Prediction:
 [[0.03992063]
 [0.5303372 ]
 [0.32244718]
 [0.09323466]
 [0.18918371]
 [0.19451535]
 [0.14121419]
 [0.3011319 ]]
5 Cost:  0.07246317 
Prediction:
 [[0.03991431]
 [0.5303291 ]
 [0.3224398 ]
 [0.09322816]
 [0.18917686]
 [0.1945085 ]
 [0.14120752]
 [0.30112463]]
6 Cost:  0.072459854 
Prediction:
 [[0.03990802]
 [0.530321  ]
 [0.32243246]
 [0.09322166]
 [0.18917   ]
 [0.19450164

값이 [0,1]  사이에 있는거 확인 가능하다